### PR TITLE
+ handleErrors

### PR DESCRIPTION
**Pull request by reactormonk**
Didn't build with `pulp` because one of the dependencies isn't on 0.13 yet. I was lazy and `spago init` and `jq` made quick work.

### CODE REVIEW

**Comment by reactormonk** [comment]
Didn't build with `pulp` because one of the dependencies isn't on 0.13 yet. I was lazy and `spago init` and `jq` made quick work.

**Comment by natefaubion** [comment]
What is the dependency that needs to be moved to 0.13?

**Comment by reactormonk** [comment]
Honestly, I didn't check. Spago makes it too easy :-/.

**Comment by natefaubion** [comment]
I think this is useful, but I don't want to commit all the spago stuff at this time. Do you mind pushing a change that just has the changes for `handleErrors`?

**Pull request merged**
